name: Test, Build and Release staging apk
on: 
 pull_request:
   branches:
      - main
jobs:
  design_system_job:
    name: Run test Design system component
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./erifaz_ds
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.1'
      - run: flutter pub get
      - run: flutter test
  main_app_job:
    needs: design_system_job
    name: Build Main app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mainapp
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.1'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --flavor staging --debug --split-per-abi
  